version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: stockdashx
      POSTGRES_PASSWORD: stockdashx
      POSTGRES_DB: stockdashx_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stockdashx.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: